2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_setup.py:_flush():67] Configure stats pid to 3123398
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_setup.py:_flush():67] Loading settings from /home/dapgrad/tenzinl2/.config/wandb/settings
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_setup.py:_flush():67] Loading settings from /home/dapgrad/tenzinl2/lumina/tabel_extractor/wandb/settings
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/dapgrad/tenzinl2/lumina/tabel_extractor/wandb/run-20250309_224726-6o2bgpej/logs/debug.log
2025-03-09 22:47:26,980 INFO    MainThread:3123398 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/dapgrad/tenzinl2/lumina/tabel_extractor/wandb/run-20250309_224726-6o2bgpej/logs/debug-internal.log
2025-03-09 22:47:26,981 INFO    MainThread:3123398 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:47:26,981 INFO    MainThread:3123398 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'batch_size': 1, 'learning_rate': 0.001, 'epochs': 50, 'mixed_precision': True, 'model_type': 'TableSense', 'optimizer': 'Adam', 'num_gpus': 4, 'num_workers': 8, 'annotation_file': '/home/dapgrad/tenzinl2/lumina/luminaData/processed_enron_paths_filtered.csv', '_wandb': {}}
2025-03-09 22:47:26,981 INFO    MainThread:3123398 [wandb_init.py:init():784] starting backend
2025-03-09 22:47:26,981 INFO    MainThread:3123398 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:47:26,989 INFO    MainThread:3123398 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-09 22:47:26,989 INFO    MainThread:3123398 [wandb_init.py:init():803] backend started and connected
2025-03-09 22:47:26,990 INFO    MainThread:3123398 [wandb_init.py:init():896] updated telemetry
2025-03-09 22:47:26,991 INFO    MainThread:3123398 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 22:47:27,376 INFO    MainThread:3123398 [wandb_init.py:init():995] starting run threads in backend
2025-03-09 22:47:27,607 INFO    MainThread:3123398 [wandb_run.py:_console_start():2377] atexit reg
2025-03-09 22:47:27,607 INFO    MainThread:3123398 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:47:27,607 INFO    MainThread:3123398 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:47:27,607 INFO    MainThread:3123398 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-09 22:47:27,610 INFO    MainThread:3123398 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-09 22:47:29,523 INFO    MainThread:3123398 [wandb_watch.py:_watch():71] Watching
2025-03-09 22:48:13,758 WARNING MsgRouterThr:3123398 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/dapgrad/tenzinl2/lumina/lumina/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dapgrad/tenzinl2/lumina/lumina/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dapgrad/tenzinl2/lumina/lumina/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dapgrad/tenzinl2/lumina/lumina/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/dapgrad/tenzinl2/lumina/lumina/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 22:48:13,761 INFO    MsgRouterThr:3123398 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
